name: myci

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-18.04]

      fail-fast: false

    steps:

      - name: setup
        run: echo "${HOME}/opt/conda/bin" >> $GITHUB_PATH

      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: dependency (ubuntu)
        if: matrix.os != 'macos-latest'
        run: |
          sudo apt-get -qy install python

      - name: test(python)
        run: |
          make test
